### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by teitei-tk** [teitei-tk/bravia-mqtt-aws#8]
# TODO feature

## Goal
- [ ] publish Alexa skill
- [ ] subscribe Alexa message in AWS lambda
- [ ] control bravia tv things
- [ ] publish bravia control message to AWS IoT(RaspberryPi)
- [ ] change TV control in RaspberryPi

## 0.0.2
- [ ] control things
- [ ] deploy publisher to AWS Lambda

## 0.0.1
- [x] aws
  - [x] certificate manage
- [ ] subscriber
  - [ ] print publish message
- [ ] publisher
  - [ ] push message to subscriber

## 0.0.0
- [x] Typescript Setting
- [x] monorepo architecture with lerna and yarn workspace
- [x] prettier setup
- [x] tslint setup
- [x] aws-cli setup with pyenv and pipenv
- [x] write setup document without aws iot
